import type { Exam } from "@/lib/exams/types";

/**
 * 첫 시험: 기초 용어 이해도 테스트.
 * ⚠️ 샘플 문항이다. 실제 문제 소스가 정해지면 교체한다.
 */
export const basicTermsExam: Exam = {
  id: "basic-terms",
  title: "Poker Basics — 기초 용어",
  domain: "Fundamentals",
  skill: "Terminology",
  description: "포지션, 액션, 핸드 표기 등 포커 테이블에서 쓰이는 기본 용어를 이해하고 있는지 확인합니다.",
  difficulty: 1,
  questions: [
    {
      id: "bt-01",
      kind: "term",
      category: "Positions",
      difficulty: 1,
      prompt: "BTN(버튼) 포지션의 특징으로 옳은 것은?",
      choices: [
        { id: "a", text: "프리플랍에서 가장 먼저 행동한다" },
        { id: "b", text: "포스트플랍에서 가장 마지막에 행동한다" },
        { id: "c", text: "항상 빅블라인드를 낸다" },
        { id: "d", text: "스몰블라인드 바로 왼쪽 자리다" },
      ],
      answer: "b",
      explanation: "BTN은 딜러 위치로, 플랍 이후 모든 스트리트에서 가장 마지막에 행동하는 유리한 자리입니다.",
    },
    {
      id: "bt-02",
      kind: "term",
      category: "Positions",
      difficulty: 1,
      prompt: "SB와 BB가 카드를 받기 전에 의무적으로 내는 칩을 무엇이라고 하나?",
      choices: [
        { id: "a", text: "앤티(Ante)" },
        { id: "b", text: "블라인드(Blind)" },
        { id: "c", text: "레이크(Rake)" },
        { id: "d", text: "사이드팟(Side pot)" },
      ],
      answer: "b",
      explanation: "SB(스몰블라인드)와 BB(빅블라인드)는 매 핸드 강제로 내는 베팅입니다.",
    },
    {
      id: "bt-03",
      kind: "term",
      category: "Positions",
      difficulty: 1,
      prompt: "UTG(Under the Gun)는 어떤 자리인가?",
      choices: [
        { id: "a", text: "프리플랍에서 가장 먼저 행동하는 자리" },
        { id: "b", text: "버튼 바로 오른쪽 자리" },
        { id: "c", text: "빅블라인드 자리" },
        { id: "d", text: "칩이 가장 많은 플레이어" },
      ],
      answer: "a",
      explanation: "UTG는 빅블라인드 바로 왼쪽으로, 프리플랍에서 가장 먼저 행동합니다.",
    },
    {
      id: "bt-04",
      kind: "term",
      category: "Positions",
      difficulty: 2,
      prompt: "CO(Cutoff)는 어디인가?",
      choices: [
        { id: "a", text: "스몰블라인드 바로 왼쪽" },
        { id: "b", text: "UTG 바로 왼쪽" },
        { id: "c", text: "버튼 바로 오른쪽" },
        { id: "d", text: "빅블라인드 바로 오른쪽" },
      ],
      answer: "c",
      explanation: "CO는 BTN 바로 앞(오른쪽) 자리로, BTN 다음으로 포지션이 좋습니다.",
    },
    {
      id: "bt-05",
      kind: "term",
      category: "Stacks",
      difficulty: 1,
      prompt: "“스택이 40BB”라는 말의 의미는?",
      choices: [
        { id: "a", text: "칩이 40개 있다" },
        { id: "b", text: "빅블라인드 40개에 해당하는 칩을 가지고 있다" },
        { id: "c", text: "40번째 핸드를 플레이 중이다" },
        { id: "d", text: "블라인드 레벨이 40이다" },
      ],
      answer: "b",
      explanation: "스택을 빅블라인드 단위로 표현하면 블라인드 크기와 관계없이 스택 깊이를 비교할 수 있습니다.",
    },
    {
      id: "bt-06",
      kind: "term",
      category: "Actions",
      difficulty: 2,
      prompt: "RFI(Raise First In)란?",
      choices: [
        { id: "a", text: "누군가의 레이즈에 다시 레이즈하는 것" },
        { id: "b", text: "앞 사람들이 모두 폴드했을 때 처음으로 레이즈하며 들어가는 것" },
        { id: "c", text: "블라인드 금액만큼만 콜하고 들어가는 것" },
        { id: "d", text: "올인으로 들어가는 것" },
      ],
      answer: "b",
      explanation: "RFI는 팟에 아무도 참여하지 않았을 때 첫 번째로 레이즈하며 참여하는 액션입니다.",
    },
    {
      id: "bt-07",
      kind: "term",
      category: "Actions",
      difficulty: 2,
      prompt: "프리플랍에서 3Bet이란?",
      choices: [
        { id: "a", text: "세 명이 콜한 팟" },
        { id: "b", text: "빅블라인드의 3배로 오픈하는 것" },
        { id: "c", text: "첫 레이즈(오픈)에 대해 다시 레이즈하는 것" },
        { id: "d", text: "세 번째 스트리트에서 베팅하는 것" },
      ],
      answer: "c",
      explanation: "프리플랍에서는 블라인드를 1벳, 오픈 레이즈를 2벳으로 보기 때문에 그에 대한 리레이즈가 3Bet입니다.",
    },
    {
      id: "bt-08",
      kind: "term",
      category: "Actions",
      difficulty: 1,
      prompt: "림프(Limp)란?",
      choices: [
        { id: "a", text: "레이즈 없이 빅블라인드 금액만 콜하고 팟에 들어가는 것" },
        { id: "b", text: "카드를 보지 않고 베팅하는 것" },
        { id: "c", text: "작은 금액으로 베팅하는 것" },
        { id: "d", text: "핸드를 포기하는 것" },
      ],
      answer: "a",
      explanation: "림프는 프리플랍에서 레이즈하지 않고 빅블라인드만큼 콜하며 참여하는 것입니다.",
    },
    {
      id: "bt-09",
      kind: "term",
      category: "Actions",
      difficulty: 2,
      prompt: "C-bet(Continuation Bet)이란?",
      choices: [
        { id: "a", text: "콜한 사람이 플랍에서 먼저 베팅하는 것" },
        { id: "b", text: "프리플랍 레이저가 플랍에서 이어서 베팅하는 것" },
        { id: "c", text: "같은 금액을 계속 베팅하는 것" },
        { id: "d", text: "리버에서 올인하는 것" },
      ],
      answer: "b",
      explanation: "프리플랍의 공격을 이어간다는 의미로, 프리플랍 마지막 레이저가 다음 스트리트에서 베팅하는 것입니다.",
    },
    {
      id: "bt-10",
      kind: "term",
      category: "Hand Notation",
      difficulty: 1,
      prompt: "핸드 표기 ‘AKs’에서 s의 의미는?",
      choices: [
        { id: "a", text: "Strong — 강한 핸드" },
        { id: "b", text: "Suited — 두 카드의 무늬가 같음" },
        { id: "c", text: "Straight — 스트레이트 가능" },
        { id: "d", text: "Small — 작은 카드 포함" },
      ],
      answer: "b",
      explanation: "s는 Suited(같은 무늬), o는 Offsuit(다른 무늬)를 뜻합니다.",
    },
    {
      id: "bt-11",
      kind: "term",
      category: "Streets",
      difficulty: 1,
      prompt: "플랍(Flop)이란?",
      choices: [
        { id: "a", text: "처음 공개되는 커뮤니티 카드 3장" },
        { id: "b", text: "네 번째로 공개되는 카드 1장" },
        { id: "c", text: "마지막으로 공개되는 카드 1장" },
        { id: "d", text: "각 플레이어가 받는 개인 카드 2장" },
      ],
      answer: "a",
      explanation: "커뮤니티 카드는 플랍(3장) → 턴(1장) → 리버(1장) 순서로 공개됩니다.",
    },
    {
      id: "bt-12",
      kind: "term",
      category: "Game Types",
      difficulty: 1,
      prompt: "MTT는 무엇의 약자인가?",
      choices: [
        { id: "a", text: "Multi-Table Tournament" },
        { id: "b", text: "Max Table Tempo" },
        { id: "c", text: "Main Table Timer" },
        { id: "d", text: "Multi-Turn Tactic" },
      ],
      answer: "a",
      explanation: "여러 테이블에서 동시에 진행되며 탈락자가 생기는 토너먼트 방식입니다.",
    },
  ],
};
